confirm-before-quit = false
line-height = 1
working-dir = "/home/"

[cursor]
blinking = true
shape = "beam"

[editor]
program = "zeditor"

[fonts]
family = "IBM Plex Mono"
size = 16

[navigation]
unfocused-split-opacity = 0.8

[renderer]
backend = "Automatic"
disable-unfocused-render = true
performance = "Low"

[window]
blue = true
decorations = "Enabled"
opacity = 0.9
